theme: jekyll-theme-minimal
title: Space Dog XR
description: Space Dog XR is an indie game dev studio based in NYC that focuses on Virtual and Augmented Reality (XR) experiences.
logo: space_dog_xr_logo.png
